tools: Fix package prereqs in builder container
Install the btrfsprogs package in the builder container to fix the following error message when building the Aquarium Vagrant image.

[ INFO    ]: 13:23:12 | Precalculating required disk size
[ INFO    ]: 13:23:12 | --> system data with filesystem overhead needs 1390 MB
[ INFO    ]: 13:23:12 | --> legacy bios boot partition adding 2 MB
[ INFO    ]: 13:23:12 | --> spare partition adding 5120 MB
[ INFO    ]: 13:23:12 | --> EFI partition adding 20 MB
[ INFO    ]: 13:23:12 | Using configured disk size: 24576 MB
[ INFO    ]: 13:23:12 | Creating raw disk image /builder/out/aqr-main-20211103.01/_out/project-aquarium.x86_64-16.0.0.raw
[ INFO    ]: 13:23:14 | --> creating EFI CSM(legacy bios) partition
[ INFO    ]: 13:23:16 | --> creating EFI partition
[ INFO    ]: 13:23:18 | --> creating root partition
[ INFO    ]: 13:23:21 | --> creating spare partition
[ ERROR   ]: 13:23:23 | KiwiCommandNotFound: Command "mkfs.btrfs" not found in the environment
[ INFO    ]: 13:23:23 | Cleaning up FileSystemBtrfs instance
[ INFO    ]: 13:23:23 | Cleaning up Disk instance
[ INFO    ]: 13:23:23 | Cleaning up LoopDevice instance
[ INFO    ]: 13:23:23 | Cleaning up BootLoaderConfigGrub2 instance
+ '[' 1 -eq 0 ']'
+ error_exit 'Kiwi build failed'
+ echo 'error: Kiwi build failed'
error: Kiwi build failed

Signed-off-by: Volker Theile <vtheile@suse.com>